### PR TITLE
Apple clone webpage

### PR DESCRIPTION
**Pull request by MuriloRoque**
[Live Link](https://raw.githack.com/MuriloRoque/apple-clone-webpage/home-page/index.html)

In this project, I used:

- Flex for alignment and positioning;
- Background image properties;
- Gradients inside of elements in the navbar.

### CODE REVIEW

**Comment by majovanilla** [comment]
Hey @MuriloRoque , 👋

## You did a *great* job on this project! 💜 

- Good Readme file
- Good Pull Request Message
- The page looks amazing

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- You did a great job with the navbar, now please take a look at the screenshots and improve the details: your apple logo should be white, your search icon should be white.

- Your navbar uses buttons for each element. That is not the right use of a button, read this [article](https://developer.mozilla.org/en/docs/Web/HTML/Element/button) and [this one](https://stackoverflow.com/questions/21715162/when-should-i-use-a-button-button-or-a-link-a-in-html) to see why you should use an `<a>` tag instead. Please change this.

Your page:
Screenshot from 2020-03-05 17-38-45

Original:
Screenshot from 2020-03-05 17-39-24

- You don't need to use a `<form>`  tag on the search bar, you just need an `<input>` for it.

- Your bottom images should be links `<a>` Right now they are ``. Just w

- Check this icon. In your page is black and it should be white.
Screenshot from 2020-03-05 17-58-57
Screenshot from 2020-03-05 17-59-02


### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You could include the hover effects on the main titles.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by MuriloRoque** [comment]
Hi, here are the changes made after the TSE review:

**REQUIRED**

- **Apple and search icons:** Colors changed to white. ✔️
- **Navbar buttons:** I understood the difference between the button and link usage and changed them, thanks for the feedback! ✔️:
- **Form tag:** Removed! ✔️
- **Bottom images:** The TSE comment is not finished, but I think Maria told me to just wrap the images inside links, did that! ✔️ 
- **Play button:** Color changed to white. ✔️

**OPTIONAL**

**Included a hover effect on the last title:** The problem is that the font I used was giving me a thick underline and I wanted a thinner one. What I did was use a linear gradient to make the hover effect, I think it worked! 😄

**Comment by lekegitrepo** [comment]
### Hi @MuriloRoque 👍 
**_The page looks great, I'll also like to commend how you pay attention to details._**

However, based on the previous review, you still need to complete the following requirements:
- Apple logo should be white, your search icon should be white and also the play icon
as mentioned in the previous review.

apple

**_Make the changes and submit for review_**

**_If you have any doubt or question contact me on slack._**

### Reviewed by: Temitayo Adeleke

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by MuriloRoque** [comment]
Hi @lekegitrepo!

Actually, I already made these changes, can you please check the [Live link](https://raw.githack.com/MuriloRoque/apple-clone-webpage/home-page/index.html) again? I think it takes a while to update 😄 thank you!

**Comment by lekegitrepo** [comment]
Okay

**Comment by lekegitrepo** [comment]
Oh!! I can see it now, but I've already submitted the form.
I'm so sorry I believe it's my mistake.
but can you please 🙏  just submit this pull request again?

**Comment by MuriloRoque** [comment]
Of course! Also, I updated the README file screenshot, I'll send the form again!

**Comment by lekegitrepo** [comment]
Thanks

**Comment by lekegitrepo** [comment]
# Excellent job 💯  💯 
## This project is approved. Good luck with the next project.

**Review by lekegitrepo — APPROVED** [review]
# Approved

**Pull request merged**
